#!/usr/bin/env bash
# Builds package/ for local testing (e.g. from a consuming project via a `file:` dependency)
# — no npm publish involved. Copies the already-built vendor/sharp (JS + native
# addon) and our custom libvips-cpp.so into package/linux-x64/, alongside the
# static package.json/index.js dispatcher (those aren't regenerated by this
# script — edit them directly if the dispatch logic needs to change).
set -euo pipefail
cd "$(dirname "$0")/.."

# Derived, not hardcoded — a version bump should only need to touch the
# submodule pins (and package/package.json, via scripts/release.sh).
SHARP_SRC="vendor/sharp"
SHARP_VERSION=$(node -p "require('./$SHARP_SRC/package.json').version")
VERSION_VIPS=$(grep '^VERSION_VIPS=' vendor/sharp-libvips/versions.properties | cut -d= -f2)
LIBVIPS_SO="dist/linux-x64/lib/libvips-cpp.so.${VERSION_VIPS}"
PKG_DIR="package"

if [ ! -f "$SHARP_SRC/src/build/Release/sharp-linux-x64-${SHARP_VERSION}.node" ]; then
  echo "error: $SHARP_SRC hasn't been built yet (missing src/build/Release/sharp-linux-x64-${SHARP_VERSION}.node)" >&2
  exit 1
fi
if [ ! -f "$LIBVIPS_SO" ]; then
  echo "error: $LIBVIPS_SO not found — run the Phase A libvips build first" >&2
  exit 1
fi

rm -rf "$PKG_DIR/linux-x64"
mkdir -p "$PKG_DIR/linux-x64/sharp/src/build/Release"
mkdir -p "$PKG_DIR/linux-x64/sharp/node_modules/@img"

cp -r "$SHARP_SRC/dist" "$PKG_DIR/linux-x64/sharp/dist"
cp "$SHARP_SRC/package.json" "$PKG_DIR/linux-x64/sharp/package.json"
cp "$SHARP_SRC/src/build/Release/sharp-linux-x64-${SHARP_VERSION}.node" "$PKG_DIR/linux-x64/sharp/src/build/Release/"

# Only the 3 runtime deps sharp's dist/*.cjs actually requires at runtime —
# not the full node_modules (which also has ~250MB of other platforms'
# prebuilt @img/sharp-libvips-* / @img/sharp-* optional deps we don't need).
cp -r "$SHARP_SRC/node_modules/detect-libc" "$PKG_DIR/linux-x64/sharp/node_modules/"
cp -r "$SHARP_SRC/node_modules/semver" "$PKG_DIR/linux-x64/sharp/node_modules/"
cp -r "$SHARP_SRC/node_modules/@img/colour" "$PKG_DIR/linux-x64/sharp/node_modules/@img/"

# libvips-cpp.so lives right next to the .node addon, and we set the addon's
# RPATH to $ORIGIN (below) so the dynamic linker finds it there deterministically.
# Earlier attempt: setting process.env.LD_LIBRARY_PATH from within index.js
# before requiring the addon. That's unreliable — glibc parses LD_LIBRARY_PATH
# once at process start, not per dlopen() call; it happened to get the addon's
# own initial load working but still segfaulted on the actual decode path.
#
# Important: use --force-rpath to get old-style DT_RPATH, not patchelf's
# default DT_RUNPATH. RUNPATH is checked *after* LD_LIBRARY_PATH; RPATH is
# checked *before* it. Found this the hard way in a real consuming project:
# with RUNPATH, an unrelated LD_LIBRARY_PATH entry (or a leftover, unpatched
# libvips-cpp.so.8.18.3 elsewhere in that project's node_modules — e.g. from a
# direct `sharp` import that wasn't overridden) can silently win over this
# co-located, patched copy, since it's checked first. Old-style RPATH always
# wins for our own direct NEEDED entry, regardless of the consumer's environment.
cp "$LIBVIPS_SO" "$PKG_DIR/linux-x64/sharp/src/build/Release/"
ln -sf "$(basename "$LIBVIPS_SO")" "$PKG_DIR/linux-x64/sharp/src/build/Release/libvips-cpp.so"

docker run --rm \
  -v "$PWD:$PWD" -w "$PWD" \
  sharp-electron-build \
  patchelf --force-rpath --set-rpath '$ORIGIN' "$PKG_DIR/linux-x64/sharp/src/build/Release/sharp-linux-x64-${SHARP_VERSION}.node"

# npmjs.com displays the published package's own README, not the repo root's —
# so the root README (the single maintained copy) gets copied in at package
# time. package/README.md is gitignored; never edit it directly.
cp README.md "$PKG_DIR/README.md"

# package/package.json declares real `sharp` as a dependency, for the
# non-Linux fallback in index.js. That's all a real `npm publish` needs — npm
# resolves it normally for any consumer. But an out-of-tree `file:` dependency
# (what local testing uses) is a special case: npm does NOT recursively
# install a file:-referenced package's own dependencies the way it does for a
# normal registry package, so package/ needs its own node_modules populated
# here, or the non-Linux branch would fail to resolve `sharp` in a local test.
(cd "$PKG_DIR" && npm install --omit=dev --no-package-lock >/dev/null)

echo "Packaged into $PKG_DIR/linux-x64/ ($(du -sh "$PKG_DIR/linux-x64" | cut -f1))"
